development:
  adapter: postgresql
  encoding: unicode
  database: EmotionAll_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: EmotionAll_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: EmotionAll_production
  pool: 5
  username:
  password:
